# Generated by Django 5.0.1 on 2024-01-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_novela_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['nombreDelAnime']},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['nombreDelManga']},
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='seudonimo',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='nombre',
            new_name='nombreDelAnime',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='seudonimo',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='nombre',
            new_name='nombreDelManga',
        ),
    ]
