# Generated by Django 5.0.1 on 2024-01-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_anime_options_alter_manga_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={'ordering': ['nombreDelJuego']},
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='nombre',
            new_name='nombreDelJuego',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fechaDeEntrega',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='autor',
            field=models.CharField(default='autor', max_length=30),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='email',
            field=models.EmailField(default='desconocido', max_length=254),
            preserve_default=False,
        ),
    ]
