# Generated by Django 5.0.1 on 2024-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_videojuego_autor_videojuego_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombreDelJuego',
            field=models.CharField(max_length=100),
        ),
    ]
