# Generated by Django 5.0.1 on 2024-01-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_videojuego_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='autor',
            field=models.CharField(default='autor', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='fecha',
            field=models.DateField(),
        ),
    ]
