# Generated by Django 5.0.1 on 2024-01-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_videojuego_autor_alter_videojuego_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha',
        ),
    ]
